### ISSUE TITLE
[Feature Request] Creating Scenarios on M8190a

### ISSUE THREAD

**Issue by jaredmann16** [morgan-at-keysight/pyarbtools#15]
With the pyarbtools, is it possible to create segments and/or scenarios so that the M8190 can output multiple signals on one channel?

**Comment by morgan-at-keysight** [comment]
Hi Jared, thanks for the request.

PyArbTools doesn't support sequencing or scenario building in the M819X AWGs right now. If you need an immediate solution, you can still send SCPI commands to your AWG using the .write() method and set up sequencing manually.

Check out [this Python script](https://github.com/morgan-at-keysight/instrument-control-examples/blob/master/Python/awg_pulse_sequence.py) to see an example of using the sequencer manually on an M8190A.

I would like to add sequencing capability to PyArbTools, and this seems like a good opportunity to start working on it.

**Comment by jaredmann16** [comment]
Hi Morgan, thank you for the python code.

I was looking over the idlesamples part of the code and was wondering if the idlesamples were directly related to setting the PRI of the signal you are sending? I ended up editing the code a bit to allow for scenarios which in turn changed the res mode to wpr. However, when running the code, the PRI set does not seem to match up with the PRI seen on the oscilloscope I am using. Any ideas on what could be causing this?

Thank you.

**Comment by morgan-at-keysight** [comment]
Hi Jared, happy to help.

Yes, "idlesamples" _directly and intentionally_ impacts the PRI of a pulse. There are a lot of things to consider when working with the idle segment in the sequencer, but once you take them into account it's a _very powerful_ tool.

Can you use sequence mode instead of scenario mode in your application? I've not ever run into a situation where I needed to use a scenario over a sequence. 

Unexpected PRI values could stem from a number of different issues, including incorrectly calculating the number of idle samples required, not taking the length of the "end cap" waveform into account (see lines 107-114 in the Python code linked earlier) , and unexpected/unintended sample rate settings.

How much different is the PRI? Is it orders of magnitude? Does your pulse width also change by the same factor?

**Comment by morgan-at-keysight** [comment]
@jaredmann16 were you able to look at the PRI values again?
