### ISSUE TITLE
[minor bugs] Install error due to path and file name of HISTORY.rst

### ISSUE THREAD

**Issue by prettypoly** [morgan-at-keysight/pyarbtools#37]
1. SYSTEM INFO: Ubuntu WSL 2

2. ERROR MESSAGE:
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    with open('docs\HISTORY.rst') as history_file:
FileNotFoundError: [Errno 2] No such file or directory: 'docs\\HISTORY.rst'

3. HOW TO REPRODUCE:
`git clone --depth 1 https://github.com/morgan-at-keysight/pyarbtools.git`
`cd pyarbtools`
`python setup.py install`

4. REASON WHY THIS HAPPENED:
Directory names in a path are separated with / on Unix or Linux, but \ on Windows.
File names are case sensitive.

5. HOW TO FIX:
change 
`with open('docs\HISTORY.rst') as history_file:` 
to
`with open('./docs/history.rst') as history_file:`

**Comment by morgan-at-keysight** [comment]
Does this error also occur when installing via pip?

**Comment by prettypoly** [comment]
No, Morgan, I have just installed it using pip. No errors. 
The error only occurs if you install it from a cloned local repo.
Emm.. then I guess pip is a more reliable way to install.

**Comment by morgan-at-keysight** [comment]
To be perfectly honest, I have not tested PyArbTools on Linux very much, so OS-specific behavior management is not something I've spent much time with.

For now, I would highly recommend using pip to install rather than installing from a cloned repo. I have not seen any issues with that method. 

Closing issue for now. Feel free to reopen later if you _absolutely need_ to be able to install from a cloned repo.
